spring.application.name=springoauth2demo

# Server port (optional, defaults to 8080)
server.port=3000

# AuthAction config
authaction.domain=authaction-tenant-domain
authaction.audience=authaction-api-identifier
